-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 516cc9fa72ad09699f2c03ffbd0aa7f60d75b59a
    hooks:
    -   id: trailing-whitespace
-   repo: /Users/Zonito/Softwares/Codes/command-hook
    sha: 5fa10afa7e9b2ef41e5478ccc6886b5b7f2521f1
    hooks:
    -   id: command
